// Code generated by hertz generator.

package v1

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listassetsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createassetMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _assetsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getassetMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateassetMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _assets0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateassetstatusMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateassetarchiveMw() []app.HandlerFunc {
	// your code...
	return nil
}
