// Code generated by hertz generator; handler implementations are maintained here.
// hz update preserves existing handlers and appends new RPC handlers.
package v1

import (
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	model "github.com/moyin1004/suirenx/services/api/biz/model/suirenx/asset/v1"
	"github.com/moyin1004/suirenx/services/api/internal/service"
)

// ListAssets handles the list RPC declared in asset.proto.
// @router /api/v1/assets [GET]
func ListAssets(_ context.Context, c *app.RequestContext) {
	var req model.ListAssetsRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, map[string]string{"error": "invalid request query"})
		return
	}
	assets, err := assetService(c).ListScope(req.Status, req.Scope)
	if err != nil {
		writeError(c, err)
		return
	}
	response := &model.ListAssetsResponse{Assets: make([]*model.Asset, 0, len(assets))}
	for _, asset := range assets {
		response.Assets = append(response.Assets, toAPIAsset(asset))
	}
	c.JSON(consts.StatusOK, response)
}

// CreateAsset handles the create RPC declared in asset.proto.
// @router /api/v1/assets [POST]
func CreateAsset(_ context.Context, c *app.RequestContext) {
	var req model.CreateAssetRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, map[string]string{"error": "invalid request body"})
		return
	}
	asset, err := assetService(c).Create(service.CreateAssetInput{
		Name: req.Name, PriceCents: req.PriceCents, PurchaseDate: req.PurchaseDate, ImageURL: req.ImageUrl,
	})
	if err != nil {
		writeError(c, err)
		return
	}
	c.JSON(consts.StatusCreated, &model.CreateAssetResponse{Asset: toAPIAsset(asset)})
}

// GetAsset handles the get RPC declared in asset.proto.
// @router /api/v1/assets/:id [GET]
func GetAsset(_ context.Context, c *app.RequestContext) {
	var req model.GetAssetRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, map[string]string{"error": "invalid request path"})
		return
	}
	asset, err := assetService(c).Get(req.Id)
	if err != nil {
		writeError(c, err)
		return
	}
	c.JSON(consts.StatusOK, &model.GetAssetResponse{Asset: toAPIAsset(asset)})
}

// UpdateAsset handles the update RPC declared in asset.proto.
// @router /api/v1/assets/:id [PUT]
func UpdateAsset(_ context.Context, c *app.RequestContext) {
	var req model.UpdateAssetRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, map[string]string{"error": "invalid request body"})
		return
	}
	asset, err := assetService(c).Update(service.UpdateAssetInput{
		ID: req.Id, Name: req.Name, PriceCents: req.PriceCents, PurchaseDate: req.PurchaseDate,
	})
	if err != nil {
		writeError(c, err)
		return
	}
	c.JSON(consts.StatusOK, &model.UpdateAssetResponse{Asset: toAPIAsset(asset)})
}

// UpdateAssetStatus handles lifecycle changes declared in asset.proto.
// @router /api/v1/assets/:id/status [PUT]
func UpdateAssetStatus(_ context.Context, c *app.RequestContext) {
	var req model.UpdateAssetStatusRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, map[string]string{"error": "invalid request body"})
		return
	}
	asset, err := assetService(c).UpdateStatus(service.UpdateAssetStatusInput{
		ID: req.Id, Status: req.Status, RetiredDate: req.RetiredDate,
	})
	if err != nil {
		writeError(c, err)
		return
	}
	c.JSON(consts.StatusOK, &model.UpdateAssetStatusResponse{Asset: toAPIAsset(asset)})
}

// UpdateAssetArchive handles reversible archiving declared in asset.proto.
// @router /api/v1/assets/:id/archive [PUT]
func UpdateAssetArchive(_ context.Context, c *app.RequestContext) {
	var req model.UpdateAssetArchiveRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, map[string]string{"error": "invalid request body"})
		return
	}
	asset, err := assetService(c).UpdateArchive(req.Id, req.Action)
	if err != nil {
		writeError(c, err)
		return
	}
	c.JSON(consts.StatusOK, &model.UpdateAssetArchiveResponse{Asset: toAPIAsset(asset)})
}
