// Code generated by hertz generator; handler implementations are maintained here.
// hz update preserves existing handlers and appends new RPC handlers.
package v1

import (
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	model "github.com/moyin1004/suirenx/services/api/biz/model/suirenx/asset/v1"
	"github.com/moyin1004/suirenx/services/api/internal/service"
)

// ListAssets handles the list RPC declared in asset.proto.
// @router /api/v1/assets [GET]
func ListAssets(_ context.Context, c *app.RequestContext) {
	var req model.ListAssetsRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, map[string]string{"error": "invalid request query"})
		return
	}
	assets, err := assetService(c).List(req.Status)
	if err != nil {
		writeError(c, err)
		return
	}
	response := &model.ListAssetsResponse{Assets: make([]*model.Asset, 0, len(assets))}
	for _, asset := range assets {
		response.Assets = append(response.Assets, toAPIAsset(asset))
	}
	c.JSON(consts.StatusOK, response)
}

// CreateAsset handles the create RPC declared in asset.proto.
// @router /api/v1/assets [POST]
func CreateAsset(_ context.Context, c *app.RequestContext) {
	var req model.CreateAssetRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, map[string]string{"error": "invalid request body"})
		return
	}
	asset, err := assetService(c).Create(service.CreateAssetInput{
		Name: req.Name, PriceCents: req.PriceCents, PurchaseDate: req.PurchaseDate, ImageURL: req.ImageUrl,
	})
	if err != nil {
		writeError(c, err)
		return
	}
	c.JSON(consts.StatusCreated, &model.CreateAssetResponse{Asset: toAPIAsset(asset)})
}
