// Code generated by hertz generator; handler adapters maintained by the application.
package v1

import (
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	v1 "github.com/moyin1004/suirenx/services/api/biz/model/suirenx/m5/v1"
)

func Register(_ context.Context, c *app.RequestContext) {
	dispatch[v1.AccountRequest](c, actions(c).Register)
}

func Login(_ context.Context, c *app.RequestContext) {
	dispatch[v1.AccountRequest](c, actions(c).Login)
}

func Logout(_ context.Context, c *app.RequestContext) { actions(c).Logout(c) }
