// Code generated by hertz generator.

package v1

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	v1 "github.com/moyin1004/suirenx/services/api/biz/model/suirenx/m5/v1"
)

func ReadConfigContent(_ context.Context, c *app.RequestContext) {
	dispatch[v1.ConfigKeyRequest](c, actions(c).ReadConfigContent)
}
