// Code generated by hertz generator; handler adapters maintained by the application.
package v1

import (
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	v1 "github.com/moyin1004/suirenx/services/api/biz/model/suirenx/m5/v1"
)

func SyncAssets(_ context.Context, c *app.RequestContext) {
	dispatch[v1.SyncAssetsRequest](c, actions(c).SyncAssets)
}
