// Code generated by hertz generator; handler adapters maintained by the application.
package v1

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	v1 "github.com/moyin1004/suirenx/services/api/biz/model/suirenx/m5/v1"
)

func ListWebAssets(_ context.Context, c *app.RequestContext) {
	dispatch[v1.WebAssetListRequest](c, actions(c).ListWebAssets)
}
func CreateWebAsset(_ context.Context, c *app.RequestContext) {
	dispatch[v1.WebAssetCreateRequest](c, actions(c).CreateWebAsset)
}
func GetWebAsset(_ context.Context, c *app.RequestContext) {
	dispatch[v1.WebAssetGetRequest](c, actions(c).GetWebAsset)
}
func UpdateWebAsset(_ context.Context, c *app.RequestContext) {
	dispatch[v1.WebAssetUpdateRequest](c, actions(c).UpdateWebAsset)
}
func DeleteWebAsset(_ context.Context, c *app.RequestContext) {
	dispatch[v1.WebAssetDeleteRequest](c, actions(c).DeleteWebAsset)
}
func ListWebExpiry(_ context.Context, c *app.RequestContext) {
	dispatch[v1.WebExpiryListRequest](c, actions(c).ListWebExpiry)
}
func CreateWebExpiry(_ context.Context, c *app.RequestContext) {
	dispatch[v1.WebExpiryCreateRequest](c, actions(c).CreateWebExpiry)
}
func UpdateWebExpiry(_ context.Context, c *app.RequestContext) {
	dispatch[v1.WebExpiryUpdateRequest](c, actions(c).UpdateWebExpiry)
}
func DeleteWebExpiry(_ context.Context, c *app.RequestContext) {
	dispatch[v1.WebExpiryDeleteRequest](c, actions(c).DeleteWebExpiry)
}
